### ISSUE TITLE
expired ssl cert

### ISSUE THREAD

**Issue by cirrusUK** [jgmp/8p#1]
Not sure if 8p issue or issue of the build in AUR, build fails with expired SSL cert error

**Comment by jgmp** [comment]
Thanks for your interest in 8p and for the feedback.

Could you post the output of `makepkg`?  It gives me more information on where the error is happening.

That said, I don't think the error is related to 8p. The AUR package tries to retrieve 8p's source over HTTPS.  I am guessing that the error happens there.  If so, that would mean that your computer doesn't trust GitHub's SSL certificate.  Needless to say, this shouldn't happen and suggests a malfunction on your end.

Check if the date on your computer is correct (this could be the easy fix). Or you could change this line
`source=(https://github.com/jgmp/archive/raw/master/$pkgname-$pkgver.tar.gz)`
in the PKGBUILD to
`source=(http://github.com/jgmp/archive/raw/master/$pkgname-$pkgver.tar.gz)`
defaulting back to HTTP.

**Comment by cirrusUK** [comment]
@jgmp  Thank you editing the PKGBUILD as you suggested worked well.

**Comment by cirrusUK** [comment]
Arch recently changed path of certs this might be the cause, as my clock is correct.
