### ISSUE TITLE
cant compile, ubuntu 15.05

### ISSUE THREAD

**Issue by jcvfen** [jgmp/8p#2]
i've changed all those headers like told
but I get this.

sudo make clean install                                                                       
rm -f 8p draw.o fetch.o key.o main.o mix.o play.o report.o search.o select.o string.o track.o util.o
cc -std=c99 -O2 -pedantic -Wall -Werror -Wextra -D_XOPEN_SOURCE_EXTENDED=1 -D_XOPEN_SOURCE=700 -c -o draw.o draw.c
In file included from draw.c:3:0:
draw.h:6:24: fatal error: bsd/string.h: No such file or directory
 #include <bsd/string.h>
                        ^
compilation terminated.
Makefile:20: recipe for target 'draw.o' failed
make: *** [draw.o] Error 1

**Comment by jgmp** [comment]
It seems like you are missing a dependency.  Is libbsd-dev installed?
